version: "3.6"
services:
  netpips-api:
     build:
       args:
         VERSION: "1.0.1"
       context: .
       dockerfile: ./netpips-api/Netpips.API/Dockerfile
     depends_on:
       - netpips-sql
     container_name: netpips-api
     environment:
       - ASPNETCORE_ENVIRONMENT=ci
       - ASPNETCORE_URLS=http://*:5111
     ports:
       - "5111:5111"
     networks:
       - netpips-network

  netpips-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: netpips-sql
    ports:
      - 1433:1433
    environment:
      - ADMIN_USERNAME=SA
      - SA_PASSWORD=Password1
      - ACCEPT_EULA=Y
    networks:
      - netpips-network
networks:
  netpips-network:
    name: netpips-network